# Generated by Django 3.2 on 2023-07-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230703_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_items',
            field=models.ManyToManyField(to='product.CheckoutItem'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_code',
            field=models.IntegerField(default=75796589, null=True),
        ),
    ]
