# Generated by Django 3.2 on 2023-07-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230703_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='referece_code',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_code',
            field=models.IntegerField(default=15658715, null=True),
        ),
    ]
