# Generated by Django 4.2.3 on 2023-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_checkout_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_code',
            field=models.IntegerField(default=31904071, null=True),
        ),
    ]
