# Generated by Django 4.2.3 on 2023-07-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_checkout_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_code',
            field=models.IntegerField(default=10176207, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
