# Generated by Django 4.2.1 on 2023-06-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='product.product'),
        ),
    ]
