# Generated by Django 4.2.3 on 2023-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_checkout_order_code_alter_product_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_code',
            field=models.IntegerField(default=69789920, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
