# Generated by Django 4.2.3 on 2023-07-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_developer'),
        ('product', '0014_alter_checkout_order_code_alter_product_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_code',
            field=models.IntegerField(default=62863207, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_product', to='authentication.selleraccountmodel'),
        ),
    ]
