# Generated by Django 4.2.1 on 2023-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_address_remove_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccountmodel',
            name='phone_number',
            field=models.IntegerField(default=998),
        ),
    ]
