# Generated by Django 4.2.1 on 2023-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_buyerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'Buyer Profile', 'verbose_name_plural': 'Buyer Profile'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
