# Generated by Django 3.2 on 2023-06-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_livechatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livechatmessage',
            name='receiver',
        ),
    ]
